In [1]:
#Exercise 1

import pandas as pd
WorldHappiness = pd.read_csv('World Happiness 2019.csv')
WorldHappiness.head()

,Overall_rank,Country_or_region,Happiness_Score,GDP_per_capita,Social_support,Healthy_life_expectancy,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [4]:
#Exercise 1a
import statsmodels.api as sm

y = WorldHappiness['Happiness_Score']
X = WorldHappiness[['GDP_per_capita','Social_support','Healthy_life_expectancy','Freedom_to_make_life_choices','Generosity','Perceptions_of_corruption']]
X = sm.add_constant(X) 

model1 = sm.OLS(y,X[['const','GDP_per_capita']]).fit()
print(model1.summary())
model2 = sm.OLS(y,X[['const','Social_support']]).fit()
print(model2.summary())
model3 = sm.OLS(y,X[['const','Healthy_life_expectancy']]).fit()
print(model3.summary())
model4 = sm.OLS(y,X[['const','Freedom_to_make_life_choices']]).fit()
print(model4.summary())
model5 = sm.OLS(y,X[['const','Generosity']]).fit()
print(model5.summary())
model6 = sm.OLS(y,X[['const','Perceptions_of_corruption']]).fit()
print(model6.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        Happiness_Score   R-squared:                       0.630
Model:                            OLS   Adj. R-squared:                  0.628
Method:                 Least Squares   F-statistic:                     262.5
Date:                Thu, 25 Jun 2026   Prob (F-statistic):           4.32e-35
Time:                        11:44:04   Log-Likelihood:                -159.97
No. Observations:                 156   AIC:                             323.9
Df Residuals:                     154   BIC:                             330.0
Df Model:                           1
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const              3.3993      0.135     25.120      0.000       3.132       3.667
GDP_per_capita     2.2181      0.137     16.202      0.000       1.948       2.489
==============================================================================
Omnibus:                        1.139   Durbin-Watson:                   1.378
Prob(Omnibus):                  0.566   Jarque-Bera (JB):                1.244
Skew:                          -0.177   Prob(JB):                        0.537
Kurtosis:                       2.742   Cond. No.                         4.77
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:        Happiness_Score   R-squared:                       0.604
Model:                            OLS   Adj. R-squared:                  0.601
Method:                 Least Squares   F-statistic:                     234.7
Date:                Thu, 25 Jun 2026   Prob (F-statistic):           8.98e-33
Time:                        11:44:04   Log-Likelihood:                -165.35
No. Observations:                 156   AIC:                             334.7
Df Residuals:                     154   BIC:                             340.8
Df Model:                           1
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const              1.9124      0.235      8.140      0.000       1.448       2.377
Social_support     2.8910      0.189     15.320      0.000       2.518       3.264
==============================================================================
Omnibus:                        1.531   Durbin-Watson:                   1.298
Prob(Omnibus):                  0.465   Jarque-Bera (JB):                1.600
Skew:                          -0.197   Prob(JB):                        0.449
Kurtosis:                       2.698   Cond. No.                         8.43
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:        Happiness_Score   R-squared:                       0.608
Model:                            OLS   Adj. R-squared:                  0.606
Method:                 Least Squares   F-statistic:                     239.1
Date:                Thu, 25 Jun 2026   Prob (F-statistic):           3.79e-33
Time:                        11:44:04   Log-Likelihood:                -164.48
No. Observations:                 156   AIC:                             333.0
Df Residuals:                     154   BIC:                             339.1
Df Model:                           1
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       2.8068      0.177     15.837      0.000       2.457       3.157
Healthy_life_expectancy     3.5854      0.232     15.462      0.000       3.127       4.043
==============================================================================
Omnibus:                        6.324   Durbin-Watson:                   1.140
Prob(Omnibus):                  0.042   Jarque-Bera (JB):                3.543
Skew:                          -0.148   Prob(JB):                        0.170
Kurtosis:                       2.324   Cond. No.                         6.41
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:        Happiness_Score   R-squared:                       0.321
Model:                            OLS   Adj. R-squared:                  0.317
Method:                 Least Squares   F-statistic:                     72.87
Date:                Thu, 25 Jun 2026   Prob (F-statistic):           1.24e-14
Time:                        11:44:04   Log-Likelihood:                -207.35
No. Observations:                 156   AIC:                             418.7
Df Residuals:                     154   BIC:                             424.8
Df Model:                           1
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                            3.6788      0.215     17.075      0.000       3.253       4.104
Freedom_to_make_life_choices     4.4026      0.516      8.536      0.000       3.384       5.421
==============================================================================
Omnibus:                        4.022   Durbin-Watson:                   0.757
Prob(Omnibus):                  0.134   Jarque-Bera (JB):                4.082
Skew:                          -0.383   Prob(JB):                        0.130
Kurtosis:                       2.798   Cond. No.                         8.10
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:        Happiness_Score   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                 -0.001
Method:                 Least Squares   F-statistic:                    0.8905
Date:                Thu, 25 Jun 2026   Prob (F-statistic):              0.347
Time:                        11:44:04   Log-Likelihood:                -237.12
No. Observations:                 156   AIC:                             478.2
Df Residuals:                     154   BIC:                             484.3
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.2433      0.195     26.872      0.000       4.858       5.629
Generosity     0.8861      0.939      0.944      0.347      -0.969       2.741
==============================================================================
Omnibus:                        5.541   Durbin-Watson:                   0.014
Prob(Omnibus):                  0.063   Jarque-Bera (JB):                2.996
Skew:                          -0.067   Prob(JB):                        0.224
Kurtosis:                       2.335   Cond. No.                         10.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:        Happiness_Score   R-squared:                       0.149
Model:                            OLS   Adj. R-squared:                  0.143
Method:                 Least Squares   F-statistic:                     26.90
Date:                Thu, 25 Jun 2026   Prob (F-statistic):           6.65e-07
Time:                        11:44:04   Log-Likelihood:                -225.01
No. Observations:                 156   AIC:                             454.0
Df Residuals:                     154   BIC:                             460.1
Df Model:                           1
Covariance Type:            nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                         4.9049      0.127     38.560      0.000       4.654       5.156
Perceptions_of_corruption     4.5403      0.875      5.186      0.000       2.811       6.270
==============================================================================
Omnibus:                        6.947   Durbin-Watson:                   0.185
Prob(Omnibus):                  0.031   Jarque-Bera (JB):                7.237
Skew:                          -0.517   Prob(JB):                       0.0268
Kurtosis:                       2.792   Cond. No.                         10.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [5]:
#Exercise 1b
from statsmodels.stats.outliers_influence import variance_inflation_factor as vif

#Create a dataframe that contains the VIF values
VIF_data = pd.DataFrame() #create a pandas dataframe
VIF_data["variable"] = X.columns #create a variable that simply lists the names of the variables you picked
VIF_data["VIF"] = [vif(X,i) 
                   for i in range(len(X.columns))] #a loop that creates vif values for each variable and then puts it in the VIF column
print(VIF_data) #print the results

                       variable        VIF
0                         const  24.416985
1                GDP_per_capita   4.115838
2                Social_support   2.735651
3       Healthy_life_expectancy   3.572728
4  Freedom_to_make_life_choices   1.575090
5                    Generosity   1.224101
6     Perceptions_of_corruption   1.431594

In [6]:
#Exercise 1c
model7 = sm.OLS(y,X).fit()
print(model7.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        Happiness_Score   R-squared:                       0.779
Model:                            OLS   Adj. R-squared:                  0.770
Method:                 Least Squares   F-statistic:                     87.62
Date:                Thu, 25 Jun 2026   Prob (F-statistic):           2.40e-46
Time:                        11:44:29   Log-Likelihood:                -119.76
No. Observations:                 156   AIC:                             253.5
Df Residuals:                     149   BIC:                             274.9
Df Model:                           6
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                            1.7952      0.211      8.505      0.000       1.378       2.212
GDP_per_capita                   0.7754      0.218      3.553      0.001       0.344       1.207
Social_support                   1.1242      0.237      4.745      0.000       0.656       1.592
Healthy_life_expectancy          1.0781      0.335      3.223      0.002       0.417       1.739
Freedom_to_make_life_choices     1.4548      0.375      3.876      0.000       0.713       2.197
Generosity                       0.4898      0.498      0.984      0.327      -0.494       1.473
Perceptions_of_corruption        0.9723      0.542      1.793      0.075      -0.099       2.044
==============================================================================
Omnibus:                        8.188   Durbin-Watson:                   1.648
Prob(Omnibus):                  0.017   Jarque-Bera (JB):                7.971
Skew:                          -0.498   Prob(JB):                       0.0186
Kurtosis:                       3.483   Cond. No.                         28.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [8]:
#Exercise 2a
winequality = pd.read_csv("winequality-red.csv")
X = winequality[['fixed_acidity','volatile_acidity','citric_acid','residual_sugar','chlorides','free_sulfur_dioxide',
                 'total_sulfur_dioxide','density','pH','sulphates','alcohol']]
X = sm.add_constant(X) #add a constant to the variables. VIF WON'T WORK CORRECTLY IF YOU DON'T DO THIS
#Create a dataframe that contains the VIF values
VIF_data = pd.DataFrame() #create a pandas dataframe
VIF_data["variable"] = X.columns #create a variable that simply lists the names of the variables you picked
VIF_data["VIF"] = [vif(X,i) 
                   for i in range(len(X.columns))] #a loop that creates vif values for each variable and then puts it in the VIF column
print(VIF_data) #print the results

                variable           VIF
0                  const  1.710538e+06
1          fixed_acidity  7.767512e+00
2       volatile_acidity  1.789390e+00
3            citric_acid  3.128022e+00
4         residual_sugar  1.702588e+00
5              chlorides  1.481932e+00
6    free_sulfur_dioxide  1.963019e+00
7   total_sulfur_dioxide  2.186813e+00
8                density  6.343760e+00
9                     pH  3.329732e+00
10             sulphates  1.429434e+00
11               alcohol  3.031160e+00

In [9]:
#Exercise 2b

y = winequality['quality']
X = winequality[['fixed_acidity','volatile_acidity','citric_acid','residual_sugar','chlorides','free_sulfur_dioxide',
                 'total_sulfur_dioxide','density','pH','sulphates','alcohol']]
X = sm.add_constant(X)

model1 = sm.OLS(y,X).fit()

print(model1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                quality   R-squared:                       0.361
Model:                            OLS   Adj. R-squared:                  0.356
Method:                 Least Squares   F-statistic:                     81.35
Date:                Thu, 25 Jun 2026   Prob (F-statistic):          1.79e-145
Time:                        12:12:04   Log-Likelihood:                -1569.1
No. Observations:                1599   AIC:                             3162.
Df Residuals:                    1587   BIC:                             3227.
Df Model:                          11
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                   21.9652     21.195      1.036      0.300     -19.607      63.538
fixed_acidity            0.0250      0.026      0.963      0.336      -0.026       0.076
volatile_acidity        -1.0836      0.121     -8.948      0.000      -1.321      -0.846
citric_acid             -0.1826      0.147     -1.240      0.215      -0.471       0.106
residual_sugar           0.0163      0.015      1.089      0.276      -0.013       0.046
chlorides               -1.8742      0.419     -4.470      0.000      -2.697      -1.052
free_sulfur_dioxide      0.0044      0.002      2.009      0.045       0.000       0.009
total_sulfur_dioxide    -0.0033      0.001     -4.480      0.000      -0.005      -0.002
density                -17.8812     21.633     -0.827      0.409     -60.314      24.551
pH                      -0.4137      0.192     -2.159      0.031      -0.789      -0.038
sulphates                0.9163      0.114      8.014      0.000       0.692       1.141
alcohol                  0.2762      0.026     10.429      0.000       0.224       0.328
==============================================================================
Omnibus:                       27.376   Durbin-Watson:                   1.757
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               40.965
Skew:                          -0.168   Prob(JB):                     1.27e-09
Kurtosis:                       3.708   Cond. No.                     1.13e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.13e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [10]:
#Exercise 2c

y = winequality['quality']
X = winequality[['volatile_acidity','chlorides','free_sulfur_dioxide','total_sulfur_dioxide','pH','sulphates','alcohol']]

model2 = sm.OLS(y,X).fit()
print(model2.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                quality   R-squared (uncentered):                   0.986
Model:                            OLS   Adj. R-squared (uncentered):              0.986
Method:                 Least Squares   F-statistic:                          1.619e+04
Date:                Thu, 25 Jun 2026   Prob (F-statistic):                        0.00
Time:                        12:13:28   Log-Likelihood:                         -1629.0
No. Observations:                1599   AIC:                                      3272.
Df Residuals:                    1592   BIC:                                      3310.
Df Model:                           7
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
volatile_acidity        -1.0581      0.104    -10.127      0.000      -1.263      -0.853
chlorides               -0.8301      0.397     -2.092      0.037      -1.608      -0.052
free_sulfur_dioxide      0.0018      0.002      0.831      0.406      -0.002       0.006
total_sulfur_dioxide    -0.0019      0.001     -2.761      0.006      -0.003      -0.001
pH                       0.6345      0.061     10.348      0.000       0.514       0.755
sulphates                1.0815      0.112      9.621      0.000       0.861       1.302
alcohol                  0.3365      0.017     19.988      0.000       0.304       0.370
==============================================================================
Omnibus:                       38.457   Durbin-Watson:                   1.717
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               61.440
Skew:                          -0.215   Prob(JB):                     4.55e-14
Kurtosis:                       3.859   Cond. No.                     1.44e+03
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 1.44e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [11]:
#Exercise 3
import pandas as pd
GBvideos = pd.read_csv("GBvideos.csv")
GBvideos.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...

In [12]:
#3b

#remove variables with no likes or dislikes
GBvideos = GBvideos[GBvideos.likes > 0] #interestingly, this one is not strictly necessary because there are no videos with > 0 dislikes and 0 likes
GBvideos = GBvideos[GBvideos.dislikes > 0]
        
#Remove rows which have blocked ratings, blocked comments, or have been removed
GBvideos = GBvideos[GBvideos.comments_disabled == False] #note that in the csv file it's spelled FALSE but in Python as False. This is because it is not a string variable but a boolean
GBvideos = GBvideos[GBvideos.ratings_disabled == False]
GBvideos = GBvideos[GBvideos.video_error_or_removed == False]

In [13]:
#3c
#Create new variable
GBvideos = GBvideos.assign(like_percentage = GBvideos.likes/(GBvideos.likes+GBvideos.dislikes))

#check if there are no mistakes
GBvideos.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,like_percentage
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...,0.844573
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...,0.917645
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,0.947740
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...,0.941463
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...,0.937500

In [ ]:
#3d
from statsmodels.stats.outliers_influence import variance_inflation_factor as vif 

X = GBvideos[['views','comment_count','like_percentage']]
X = sm.add_constant(X) #add a constant to the variables. VIF WON'T WORK CORRECTLY IF YOU DON'T DO THIS

#Create a dataframe that contains the VIF values
VIF_data = pd.DataFrame() #create a pandas dataframe
VIF_data["variable"] = X.columns #create a variable that simply lists the names of the variables you picked
VIF_data["VIF"] = [vif(X,i) 
                   for i in range(len(X.columns))] #a loop that creates vif values for each variable and then puts it in the VIF column
print(VIF_data) #print the results

          variable         VIF
0            const  104.113758
1            views    1.283940
2    comment_count    1.291987
3  like_percentage    1.008589

In [16]:
import statsmodels.api as sm

y = GBvideos['like_percentage']
X = GBvideos[['views','comment_count']]
X = sm.add_constant(X)
model = sm.OLS(y,X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        like_percentage   R-squared:                       0.009
Model:                            OLS   Adj. R-squared:                  0.008
Method:                 Least Squares   F-statistic:                     163.2
Date:                Thu, 25 Jun 2026   Prob (F-statistic):           2.62e-71
Time:                        12:28:10   Log-Likelihood:                 36409.
No. Observations:               38008   AIC:                        -7.281e+04
Df Residuals:                   38005   BIC:                        -7.279e+04
Df Model:                           2
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             0.9422      0.001   1875.015      0.000       0.941       0.943
views          2.624e-10   2.82e-11      9.314      0.000    2.07e-10    3.18e-10
comment_count -1.899e-07   1.05e-08    -18.041      0.000    -2.1e-07   -1.69e-07
==============================================================================
Omnibus:                    35709.262   Durbin-Watson:                   1.990
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1415959.675
Skew:                          -4.646   Prob(JB):                         0.00
Kurtosis:                      31.421   Cond. No.                     2.11e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.11e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

In [18]:
#Exercise 4
import pandas as pd
insurance = pd.read_csv('insurance.csv')

In [16]:
#q4a: recode the variable
import numpy as np
insurance['east_west'] = np.where((insurance['region']=='southwest') | (insurance['region']=='northwest'), 1, 0)
#recode the categorical variables while we're at it
dummies = pd.get_dummies(insurance[['sex','smoker']],
                         dtype=int) #this turns them into 0s and 1s instead of true and false
insurance = pd.concat([insurance,dummies],axis=1)
insurance.head()

,age,sex,bmi,children,smoker,region,charges,east_west,sex_female,sex_male,smoker_no,smoker_yes
0,19,female,27.900,0,yes,southwest,16884.92400,1,1,0,0,1
1,18,male,33.770,1,no,southeast,1725.55230,0,0,1,1,0
2,28,male,33.000,3,no,southeast,4449.46200,0,0,1,1,0
3,33,male,22.705,0,no,northwest,21984.47061,1,0,1,1,0
4,32,male,28.880,0,no,northwest,3866.85520,1,0,1,1,0

In [19]:
#q4a: recode the variable
import numpy as np
insurance['east_west'] = np.where((insurance['region']=='southwest') | (insurance['region']=='northwest'), 1, 0)
#recode the categorical variables while we're at it
insurance = pd.get_dummies(insurance,dtype=int)
insurance.head()

,age,bmi,children,charges,east_west,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,1,1,0,0,1,0,0,0,1
1,18,33.770,1,1725.55230,0,0,1,1,0,0,0,1,0
2,28,33.000,3,4449.46200,0,0,1,1,0,0,0,1,0
3,33,22.705,0,21984.47061,1,0,1,1,0,0,1,0,0
4,32,28.880,0,3866.85520,1,0,1,1,0,0,1,0,0

In [20]:
#q4b: check for multicollinearity
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor as vif #import the VIF function


X = insurance[['age','bmi','children','east_west','sex_female','smoker_yes']] #select the relevant variables
X = sm.add_constant(X) #add a constant to the variables. VIF WON'T WORK CORRECTLY IF YOU DON'T DO THIS

#Create a dataframe that contains the VIF values
VIF_data = pd.DataFrame() #create a pandas dataframe
VIF_data["variable"] = X.columns #create a variable that simply lists the names of the variables you picked
VIF_data["VIF"] = [vif(X,i) 
                   for i in range(len(X.columns))] #a loop that creates vif values for each variable and then puts it in the VIF column
print(VIF_data) #print the results

     variable        VIF
0       const  36.154016
1         age   1.015475
2         bmi   1.030329
3    children   1.003994
4   east_west   1.021418
5  sex_female   1.008887
6  smoker_yes   1.010455

In [23]:
#q4c
import statsmodels.api as sm

y = insurance['charges']
X = insurance.drop('charges',axis=1)
X = sm.add_constant(X)

model1 = sm.OLS(y,X[['const','east_west']]).fit()
print(model1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                charges   R-squared:                       0.005
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     6.829
Date:                Thu, 25 Jun 2026   Prob (F-statistic):            0.00907
Time:                        12:54:33   Log-Likelihood:                -14474.
No. Observations:                1338   AIC:                         2.895e+04
Df Residuals:                    1336   BIC:                         2.896e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.411e+04    460.687     30.627      0.000    1.32e+04     1.5e+04
east_west  -1727.2761    660.963     -2.613      0.009   -3023.914    -430.638
==============================================================================
Omnibus:                      332.714   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              640.370
Skew:                           1.500   Prob(JB):                    8.82e-140
Kurtosis:                       4.577   Cond. No.                         2.59
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [25]:
#q4d: 
model2 = sm.OLS(y,X[['const','east_west','age']]).fit()
print(model2.summary())
model3 = sm.OLS(y,X[['const','east_west','sex_female']]).fit()
print(model3.summary())
model4 = sm.OLS(y,X[['const','east_west','bmi']]).fit()
print(model4.summary())
model5 = sm.OLS(y,X[['const','east_west','children']]).fit()
print(model5.summary())
model6 = sm.OLS(y,X[['const','east_west','smoker_yes']]).fit()
print(model6.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                charges   R-squared:                       0.095
Model:                            OLS   Adj. R-squared:                  0.093
Method:                 Least Squares   F-statistic:                     69.95
Date:                Thu, 25 Jun 2026   Prob (F-statistic):           1.29e-29
Time:                        12:57:25   Log-Likelihood:                -14411.
No. Observations:                1338   AIC:                         2.883e+04
Df Residuals:                    1335   BIC:                         2.884e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4013.5035    981.395      4.090      0.000    2088.259    5938.748
east_west  -1787.1060    630.699     -2.834      0.005   -3024.374    -549.838
age          258.2469     22.444     11.506      0.000     214.217     302.277
==============================================================================
Omnibus:                      396.151   Durbin-Watson:                   2.033
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              851.563
Skew:                           1.721   Prob(JB):                    1.22e-185
Kurtosis:                       4.852   Cond. No.                         134.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:                charges   R-squared:                       0.008
Model:                            OLS   Adj. R-squared:                  0.007
Method:                 Least Squares   F-statistic:                     5.561
Date:                Thu, 25 Jun 2026   Prob (F-statistic):            0.00394
Time:                        12:57:25   Log-Likelihood:                -14472.
No. Observations:                1338   AIC:                         2.895e+04
Df Residuals:                    1335   BIC:                         2.897e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.478e+04    561.784     26.302      0.000    1.37e+04    1.59e+04
east_west  -1709.3082    660.211     -2.589      0.010   -3004.473    -414.144
sex_female -1364.6826    659.981     -2.068      0.039   -2659.395     -69.970
==============================================================================
Omnibus:                      327.475   Durbin-Watson:                   2.010
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              624.482
Skew:                           1.482   Prob(JB):                    2.49e-136
Kurtosis:                       4.555   Cond. No.                         3.13
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:                charges   R-squared:                       0.042
Model:                            OLS   Adj. R-squared:                  0.040
Method:                 Least Squares   F-statistic:                     28.97
Date:                Thu, 25 Jun 2026   Prob (F-statistic):           4.84e-13
Time:                        12:57:25   Log-Likelihood:                -14449.
No. Observations:                1338   AIC:                         2.890e+04
Df Residuals:                    1335   BIC:                         2.892e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2111.0072   1742.318      1.212      0.226   -1306.973    5528.987
east_west  -1158.3862    653.851     -1.772      0.077   -2441.074     124.301
bmi          382.2851     53.609      7.131      0.000     277.119     487.452
==============================================================================
Omnibus:                      260.518   Durbin-Watson:                   1.984
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              430.233
Skew:                           1.292   Prob(JB):                     3.77e-94
Kurtosis:                       4.019   Cond. No.                         169.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:                charges   R-squared:                       0.010
Model:                            OLS   Adj. R-squared:                  0.009
Method:                 Least Squares   F-statistic:                     6.820
Date:                Thu, 25 Jun 2026   Prob (F-statistic):            0.00113
Time:                        12:57:25   Log-Likelihood:                -14471.
No. Observations:                1338   AIC:                         2.895e+04
Df Residuals:                    1335   BIC:                         2.896e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.336e+04    541.875     24.660      0.000    1.23e+04    1.44e+04
east_west  -1796.1832    660.068     -2.721      0.007   -3091.066    -501.300
children     712.9527    273.767      2.604      0.009     175.892    1250.013
==============================================================================
Omnibus:                      336.689   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              652.772
Skew:                           1.513   Prob(JB):                    1.79e-142
Kurtosis:                       4.597   Cond. No.                         4.26
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:                charges   R-squared:                       0.620
Model:                            OLS   Adj. R-squared:                  0.620
Method:                 Least Squares   F-statistic:                     1090.
Date:                Thu, 25 Jun 2026   Prob (F-statistic):          2.16e-281
Time:                        12:57:25   Log-Likelihood:                -13830.
No. Observations:                1338   AIC:                         2.767e+04
Df Residuals:                    1335   BIC:                         2.768e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       8695.4846    307.618     28.267      0.000    8092.018    9298.952
east_west   -520.4759    409.340     -1.271      0.204   -1323.497     282.545
smoker_yes  2.358e+04    506.978     46.501      0.000    2.26e+04    2.46e+04
==============================================================================
Omnibus:                      135.418   Durbin-Watson:                   2.022
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              211.707
Skew:                           0.724   Prob(JB):                     1.07e-46
Kurtosis:                       4.304   Cond. No.                         3.06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [26]:
#q4d(continued)
#table showing averages split up by east_west show that the bmi in the west is lower and that fewer people smoke in the west
print(insurance[['bmi','smoker_yes','east_west']].groupby('east_west').mean())

                bmi  smoker_yes
east_west
0          31.38633    0.229651
1          29.89820    0.178462